name: Tokyo Meguri
favicon: null
layout_spectrum: 0.8410826113540679
typography_spectrum: 0.76750278333202
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2894025433342904
  lightness: 0.06057977443560958
  saturation: 0.2900226751808077
  rhythmicContrast: 0.8707410402130336
purpose: []
